# GitHub Sponsors configuration
# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button

github: smallest87
custom: ['https://paypal.me/smallest87', 'https://ko-fi.com/smallest87']
